version: 2
jobs:
        build:
                working_directory: ~/tmp
                
                docker:
                        - image: python:3.7.3
                        - image: circleci/postgres:9.6.2-alpine
                          environment:
                                  POSTGRES_USER: postgres
                                  POSTGRES_DB: ca_st
                
               # docker:
               #         - image: circleci/python:3.7.3
               #           environment:
               #                 TEST_DATABASE_URL: postgresql://postgres@localhost/ca_st
               #         - image: circleci/postgres:alpine

                steps:
                        - checkout
                        - run: whoami                          
                        - run: ls ~/tmp                       
                        - run: apt-get install postgresql-client-9.6
                        - run: |
                                psql \
                                -h localhost
                                -p 5432
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_schema.sql
                        - run: |
                                psql \
                                -h localhost
                                -p 5432
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_table.sql
                                
