version: 2
jobs:
        build:
                working_directory: ~/tmp
                                
                docker:
                    - image: circleci/ruby:2.3-node
                      environment:
                        POSTGRES_HOST: 127.0.0.1
                        POSTGRES_USER: postgres
                        POSTGRES_DB: ca_st
                        RAILS_ENV: test
                    - image: circleci/postgres:9.6-alpine
                      environment:
                        POSTGRES_USER: postgres
                        POSTGRES_HOST: 127.0.0.1
                        POSTGRES_DB: ca_st                            
                        TEST_DATABASE_URL: postgresql://postgres@localhost/ca_st
                steps:
                        - checkout
                        - run: 
                            name: Install postgresql-client-9.6 
                            command: sudo apt-get update
                        - run: 
                            command: sudo apt install postgresql-client-9.6            
                        - run: 
                            command: chmod a+x ~/tmp/build_database.sh
                        - run: 
                            command: ./build_database.sh $POSTGRES_USER $POSTGRES_HOST $POSTGRES_DB
