version: 2
jobs:
        build:
                working_directory: ~/tmp
                docker:
                        - image: postgres:10
                          environment:
                                  POSTGRES_USER: postgres
                                  POSTGRES_DB: ca_st
                steps:
                        - checkout
                        - run: sudo apt-get update
                        - run: sudo apt-get install postgresql-client-9.6
                        - run: whoami                          
                        - run: ls ~/tmp                        
                        - run: |
                                psql \
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_schema.sql
                        - run: |
                                psql \
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_table.sql
                                
