version: 2
jobs:
        build:
                working_directory: ~/tmp
                                
                docker:
                    - image: circleci/ruby:2.3-node
                      environment:
                        POSTGRES_HOST: 127.0.0.1
                        POSTGRES_USER: postgres
                        RAILS_ENV: test
                    - image: circleci/postgres:9.6-alpine
                      environment:
                        POSTGRES_USER: postgres
                        POSTGRES_HOST: 127.0.0.1
                        POSTGRES_DB: ca_st                            
                        TEST_DATABASE_URL: postgresql://postgres@localhost/ca_st
                steps:
                        - checkout
                        - run: sudo apt-get update
                        - run: sudo apt install postgresql-client-9.6
                        - run: whoami                          
                        - run: ls -la ~/tmp                                            
                        - run: chmod a+x ~/tmp/build_database.sh
                        - run: ./build_tables.sh $POSTGRES_USER
                        - run: git remote -v