version: 2
jobs:
        build:
                working_directory: ~/tmp
                
                docker:
                        - image: ubuntu:16.04
                        - image: circleci/postgres:9.6.2-alpine
                          environment:
                                  POSTGRES_USER: postgres
                                  POSTGRES_DB: ca_st
                steps:
                        - checkout
                        - run:
                                  name: Install System Dependencies
                                  command: sudo apt-get update && sudo apt-get install -y postgres-client-9.6
                        - run: whoami                          
                        - run: ls ~/tmp                       
                        - run: |
                                psql \
                                -h localhost
                                -p 5432
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_schema.sql
                        - run: |
                                psql \
                                -h localhost
                                -p 5432
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_table.sql
                                
