version: 2
jobs:
        build:
                working_directory: ~/tmp
                
                # docker:
                #         - image: python:3.7.3
                #         - image: postgres:10
                #           environment:
                #                   POSTGRES_USER: postgres
                #                   POSTGRES_DB: ca_st
                
                docker:
                        - image: circleci/python:3.6.2-stretch-browsers
                          environment:
                                TEST_DATABASE_URL: postgresql://postgres@localhost/ca_st

                        - image: circleci/postgres:9.6.5-alpine-ra

                steps:
                        - checkout
                        - run: whoami                          
                        - run: ls ~/tmp                        
                        - run: |
                                psql \
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_schema.sql
                        - run: |
                                psql \
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_table.sql
                                
