version: 2
jobs:
        build:
                working_directory: ~/tmp
                
                docker:
                        - image: python:3.7.3
                        - image: circleci/postgres:9.6.2-alpine
                          environment:
                                  POSTGRES_USER: postgres
                                  POSTGRES_DB: ca_st
                
               # docker:
               #         - image: circleci/python:3.7.3
               #           environment:
               #                 TEST_DATABASE_URL: postgresql://postgres@localhost/ca_st
               #         - image: circleci/postgres:alpine

                steps:
                        - checkout
                        - run: whoami                          
                        - run: ls ~/tmp                       
                        # Use BASH instead of DASH! see: https://ubuntuforums.org/showthread.php?t=1932504
                        - run: apt-get install -y sudo # https://discuss.circleci.com/t/sudo-command-not-found/14208/4
                        - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
                        - run: sudo apt-get update
                        - run: sudo apt-get install postgresql-client-9.6
                        - run: |
                                psql \
                                -h localhost
                                -p 5432
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_schema.sql
                        - run: |
                                psql \
                                -h localhost
                                -p 5432
                                -U postgres
                                -d ca_st
                                -a -f ~/tmp/create_table.sql
                                
