version: 2
jobs:
        build:
                working_directory: ~/tmp
                                
                docker:
                    - image: circleci/ruby:2.3-node
                      environment:
                        POSTGRES_HOST: 127.0.0.1
                        POSTGRES_USER: postgres
                        POSTGRES_DB: ca_st
                        RAILS_ENV: test
                    - image: circleci/postgres:9.6-alpine
                      environment:
                        POSTGRES_USER: postgres
                        POSTGRES_HOST: 127.0.0.1
                        POSTGRES_DB: ca_st                            
                        TEST_DATABASE_URL: postgresql://postgres@localhost/ca_st
                steps:
                        - checkout
                        - run: 
                            name: Install postgresql-client-9.6 
                            command: |
                                sudo apt-get update
                                sudo apt install postgresql-client-9.6                                   
                        - run: 
                            name: Run the database build script
                            command: |
                                chmod a+x ~/tmp/build_database.sh
                                ./build_database.sh $POSTGRES_USER $POSTGRES_HOST $POSTGRES_DB
                        - run:
                            name: Testing bad syntax error
                            command: |
                                psql -X \
                                -h $POSTGRES_HOST \
                                -p 5432 \
                                -U $POSTGES_USER \
                                -d $POSTGRES_DB \
                                -c "CREATE TABLE IF NOT EXISTS mic_policy_aw.test_bad_table (mad_gid NUMBERIX(22,0)"
