CREATE OR REPLACE PROCEDURE mic_policy_aw.usp_load_mis_lookups()
LANGUAGE plpgsql
AS $$
BEGIN

	INSERT INTO mic_policy_aw.mis_lookups ( 
		MIL_SOURCE,MIL_SOURCE_ELEMENT_NAME,MIL_SOURCE_ELEMENT_VALUE,MIL_SOURCE_CONDITION,MIL_TARGET,MIL_TARGET_ELEMENT_NAME,MIL_TARGET_ELEMENT_VALUE
	)
	SELECT MIL_SOURCE,MIL_SOURCE_ELEMENT_NAME,MIL_SOURCE_ELEMENT_VALUE,MIL_SOURCE_CONDITION,MIL_TARGET,MIL_TARGET_ELEMENT_NAME,MIL_TARGET_ELEMENT_VALUE
	FROM mic_policy_aw_stage.stage_mis_lookups
	ON CONFLICT() DO UPDATE
	SET  MIL_SOURCE = EXCLUDED.MIL_SOURCE,MIL_SOURCE_ELEMENT_NAME = EXCLUDED.MIL_SOURCE_ELEMENT_NAME,MIL_SOURCE_ELEMENT_VALUE = EXCLUDED.MIL_SOURCE_ELEMENT_VALUE,MIL_SOURCE_CONDITION = EXCLUDED.MIL_SOURCE_CONDITION,MIL_TARGET = EXCLUDED.MIL_TARGET,MIL_TARGET_ELEMENT_NAME = EXCLUDED.MIL_TARGET_ELEMENT_NAME,MIL_TARGET_ELEMENT_VALUE = EXCLUDED.MIL_TARGET_ELEMENT_VALUE;
	
	COMMIT;
	
END;
$$;