CREATE TABLE IF NOT EXISTS mic_policy_aw.vw_mis_gl_ltd_prd_withd_exp (
	gid numeric(22,0),
	entity_type varchar(64),
	add_entity_type varchar(64),
	mod_entity_type varchar(64),
	del_entity_type varchar(64),
	entity_reference varchar(64),
	fk_column_name varchar(64),
	fk_column_value numeric(22,0),
	add_entity_reference varchar(64),
	mod_entity_reference varchar(64),
	del_entity_reference varchar(64),
	entity_status varchar(32),
	entity_is_locked char(1),
	id numeric(22,0),
	date_created date,
	user_created varchar(128),
	date_modified date,
	user_modified varchar(128),
	date_deleted date,
	audit_flag varchar(1),
	risk_state varchar(2),
	risk_state_stat_code varchar(2),
	risk_city_code varchar(5),
	product_code varchar(2),
	lob_code varchar(2),
	annual_premium numeric(22,0),
	transaction_premium numeric(22,0),
	written_premium numeric(22,0),
	balance_to_minimum numeric(22,0),
	deposit_premium numeric(22,0),
	full_term_premium numeric(22,0),
	trans_prem_not_sub_to_aud numeric(22,0),
	lob_prod_wthdrwl_expnse numeric(22,0),
	heading_limits varchar(1),
	occ_limit_pwc numeric(22,0),
	disp_occ_limit_pwc numeric(22,0),
	general_agg_limit_pwc numeric(22,0),
	disp_gen_agg_limit_pwc numeric(22,0),
	cut_off_date date,
	prod_withdrwl_rsk_id_code varchar(8),
	cov_basis_code varchar(8),
	policy_limits_code varchar(8),
	limits_identifier_code varchar(8),
	deduct_and_participation varchar(1),
	deductible_applies char(1),
	deductible_amount numeric(22,0),
	ded_amt_code varchar(8),
	participation_applies char(1),
	participation_percent varchar(16),
	risk_tax_code varchar(5),
	risk_county_code varchar(5),
	waived_premium numeric(22,0),
	waive_indicator varchar(2),
	prem_com_red_factor numeric(22,0),
	commissionable_premium numeric(22,0),
	prior_waived_adjustment numeric(22,0),
	is_cov_manually_rated char(1),
	comm_annual_premium numeric(22,0),
	comm_full_term_prem numeric(22,0),
	is_cov_prorated char(1)
);

ALTER TABLE mic_policy_aw.vw_mis_gl_ltd_prd_withd_exp DROP CONSTRAINT IF EXISTS vw_mis_gl_ltd_prd_withd_exp_gid;
ALTER TABLE mic_policy_aw.vw_mis_gl_ltd_prd_withd_exp ADD CONSTRAINT vw_mis_gl_ltd_prd_withd_exp_gid PRIMARY KEY (gid);

