CREATE TABLE IF NOT EXISTS mic_policy_aw.rt_mis_surcharges (
	gid numeric(22,0),
	entity_type varchar(64),
	add_entity_type varchar(64),
	mod_entity_type varchar(64),
	del_entity_type varchar(64),
	entity_reference varchar(64),
	fk_column_name varchar(64),
	fk_column_value numeric(22,0),
	add_entity_reference varchar(64),
	mod_entity_reference varchar(64),
	del_entity_reference varchar(64),
	entity_status varchar(32),
	entity_is_locked char(1),
	id numeric(22,0),
	date_created date,
	user_created varchar(128),
	date_modified date,
	user_modified varchar(128),
	option_no numeric(22,0),
	is_option_selected char(1),
	date_deleted date,
	audit_flag varchar(1),
	name varchar(128),
	type varchar(1),
	product_code varchar(2),
	lob varchar(2),
	state_code varchar(2),
	city_code varchar(12),
	annual_fee numeric(22,0),
	transaction_fee numeric(22,0),
	deposit_fee numeric(22,0),
	premium_basis numeric(22,0),
	surcharge_amount numeric(22,0),
	is_amount_in_percent char(1),
	stat_code varchar(8),
	des varchar(4000),
	full_term_fee numeric(22,0),
	total_fee numeric(22,0),
	trans_fee_not_sub_to_audit numeric(22,0),
	name_uk varchar(256),
	annual_statement_line varchar(3),
	city_name varchar(128),
	unit_coverage varchar(128),
	unit_number varchar(128),
	unit_id varchar(128),
	waived_fee numeric(22,0),
	waive_indicator varchar(2),
	handling_method varchar(8),
	waived_surcharge numeric(22,0),
	waived_tax numeric(22,0),
	waived_col_fee numeric(22,0),
	prior_surcharge_adjustment numeric(22,0),
	policy_waived_surcharge numeric(22,0),
	lob_ca_surcharge numeric(22,0),
	lob_gl_surcharge numeric(22,0)
);

ALTER TABLE mic_policy_aw.rt_mis_surcharges DROP CONSTRAINT IF EXISTS rt_mis_surcharges_gid;
ALTER TABLE mic_policy_aw.rt_mis_surcharges ADD CONSTRAINT rt_mis_surcharges_gid PRIMARY KEY (gid);

