CREATE TABLE IF NOT EXISTS mic_policy_aw.rt_mis_producers (
	gid numeric(22,0),
	entity_type varchar(64),
	add_entity_type varchar(64),
	mod_entity_type varchar(64),
	del_entity_type varchar(64),
	entity_reference varchar(64),
	fk_column_name varchar(64),
	fk_column_value numeric(22,0),
	add_entity_reference varchar(64),
	mod_entity_reference varchar(64),
	del_entity_reference varchar(64),
	entity_status varchar(32),
	entity_is_locked char(1),
	id numeric(22,0),
	date_created date,
	user_created varchar(128),
	date_modified date,
	user_modified varchar(128),
	date_deleted date,
	audit_flag varchar(1),
	producer_code varchar(10),
	display_producer_code varchar(10),
	name varchar(250),
	producer_of_record char(1),
	surplus_lines char(1),
	good_standing char(1),
	license_producer_code varchar(10),
	license_no varchar(16),
	license_states varchar(256),
	"primary" char(1),
	commission numeric(22,0),
	override_commission numeric(22,0),
	direct_bill_indicator char(1),
	sub_agent varchar(10),
	application_producer numeric(22,0),
	policy_producer numeric(22,0),
	distinguished_field_uw char(1),
	aw_submission_aw_sub_prod numeric(22,0),
	c_producer_type varchar(32),
	c_producer_group varchar(250),
	c_dragon_id varchar(64),
	c_producer_status varchar(64),
	c_internal_name varchar(250),
	c_distribution_desig varchar(64),
	c_bokerage_agrmnt varchar(64),
	c_producer_uk varchar(64),
	agency_contact varchar(4000),
	market_manager varchar(64),
	master_record_gid numeric(22,0),
	producer_contact_id numeric(22,0),
	producer_name varchar(128),
	insured_producer numeric(22,0),
	prod_concat_address varchar(128),
	license_states_desc varchar(100),
	replaced varchar(50),
	c_prod_flag varchar(1),
	policy_sub_producer numeric(22,0),
	customer_agent_info numeric(22,0)
);

ALTER TABLE mic_policy_aw.rt_mis_producers DROP CONSTRAINT IF EXISTS rt_mis_producers_gid;
ALTER TABLE mic_policy_aw.rt_mis_producers ADD CONSTRAINT rt_mis_producers_gid PRIMARY KEY (gid);

