CREATE TABLE IF NOT EXISTS mic_policy_aw.mis_risks (
	mri_policy_reference varchar(30),
	mri_coverage_part_reference varchar(30),
	mri_risk_reference varchar(30),
	mri_revision_number varchar(3),
	mri_risk_unit_number numeric(22,0),
	mri_risk_unit_type varchar(20),
	mri_risk_unit_sub_type varchar(20),
	mri_endorsement_status varchar(1),
	mri_full_term_factor numeric(22,0),
	mri_transaction_factor numeric(22,0),
	mri_annual_premium numeric(22,0),
	mri_full_term_premium numeric(22,0),
	mri_transaction_premium numeric(22,0),
	mri_tax_description varchar(50),
	mri_commissionable_premium numeric(22,0),
	mri_class varchar(6),
	mri_zip varchar(10),
	mri_county varchar(5),
	mri_territory varchar(16),
	mri_risk_state varchar(3),
	mri_tax_code varchar(5),
	mri_standard_industry_code varchar(10),
	mri_rating_plan varchar(30),
	mri_rating_plan_type varchar(30),
	mri_municipal_code varchar(5),
	mri_city_code varchar(5),
	mri_program_desc varchar(250),
	mri_territory_description varchar(50),
	mri_county_description varchar(50),
	mri_city_description varchar(50),
	mri_municipal_description varchar(50),
	mri_audit_period varchar(30),
	mri_risk_location_code varchar(6),
	mri_risk_location_code_desc varchar(30),
	mri_telephone_number varchar(12),
	mri_email_address varchar(50),
	mri_retroactive_date date,
	mri_claims_made_year varchar(1),
	mri_ext_reporting_period varchar(1),
	mri_location_code varchar(6),
	mri_ny_free_trade_zone_ind varchar(1),
	mri_comp_rate_group numeric(22,0),
	mri_defense_outside_limit varchar(1),
	mri_nyftz_class_code varchar(5),
	mri_nyftz_class_number varchar(1),
	mri_nyftz_class_description varchar(4000),
	mri_drg_ind varchar(1),
	mri_irs_ind varchar(1),
	mri_geo_ref_id numeric(22,0),
	mri_operation_type varchar(3),
	mri_operation_type_description varchar(250),
	mri_date_created date,
	mri_date_modified date,
	mri_retro_code numeric(22,0),
	mri_retro_factor numeric(22,0),
	sys_nc00054$ varchar(59)
);

ALTER TABLE mic_policy_aw.mis_risks DROP CONSTRAINT IF EXISTS mis_risks_mri_risk_reference;
ALTER TABLE mic_policy_aw.mis_risks ADD CONSTRAINT mis_risks_mri_risk_reference PRIMARY KEY (mri_risk_reference);

