CREATE TABLE IF NOT EXISTS mic_policy_aw.vw_mis_gl_emp_benefits_liab (
	gid numeric(22,0),
	entity_type varchar(64),
	add_entity_type varchar(64),
	mod_entity_type varchar(64),
	del_entity_type varchar(64),
	entity_reference varchar(64),
	fk_column_name varchar(64),
	fk_column_value numeric(22,0),
	add_entity_reference varchar(64),
	mod_entity_reference varchar(64),
	del_entity_reference varchar(64),
	entity_status varchar(32),
	entity_is_locked char(1),
	id numeric(22,0),
	date_created date,
	user_created varchar(128),
	date_modified date,
	user_modified varchar(128),
	date_deleted date,
	audit_flag varchar(1),
	risk_state varchar(2),
	risk_state_stat_code varchar(2),
	risk_city_code varchar(5),
	product_code varchar(2),
	lob_code varchar(2),
	annual_premium numeric(22,0),
	transaction_premium numeric(22,0),
	written_premium numeric(22,0),
	balance_to_minimum numeric(22,0),
	deposit_premium numeric(22,0),
	full_term_premium numeric(22,0),
	trans_prem_not_sub_to_aud numeric(22,0),
	lob_gl_ebl_dtl numeric(22,0),
	disp_each_emp_limit_ebl numeric(22,0),
	disp_aggregate_limit_ebl numeric(22,0),
	each_emp_deduct_ebl numeric(22,0),
	retroactive_date_ebp_ebl varchar(16),
	retroactive_date_ebl date,
	ext_report_prd_opt_ebl char(1),
	coverage_basis_code_ebl varchar(8),
	each_emp_limit_ebl numeric(22,0),
	aggregate_limit_ebl numeric(22,0),
	risk_tax_code varchar(5),
	risk_county_code varchar(5),
	waived_premium numeric(22,0),
	waive_indicator varchar(2),
	prem_com_red_factor numeric(22,0),
	commissionable_premium numeric(22,0),
	prior_waived_adjustment numeric(22,0),
	is_cov_manually_rated char(1),
	comm_annual_premium numeric(22,0),
	comm_full_term_prem numeric(22,0),
	is_cov_prorated char(1),
	record_date date,
	supp_ext_reporting char(1)
);

ALTER TABLE mic_policy_aw.vw_mis_gl_emp_benefits_liab DROP CONSTRAINT IF EXISTS vw_mis_gl_emp_benefits_liab_gid;
ALTER TABLE mic_policy_aw.vw_mis_gl_emp_benefits_liab ADD CONSTRAINT vw_mis_gl_emp_benefits_liab_gid PRIMARY KEY (gid);

