CREATE TABLE IF NOT EXISTS mic_policy_aw.rt_mis_comp_rating_summary (
	gid numeric(22,0),
	entity_type varchar(64),
	add_entity_type varchar(64),
	mod_entity_type varchar(64),
	del_entity_type varchar(64),
	entity_reference varchar(64),
	fk_column_name varchar(64),
	fk_column_value numeric(22,0),
	add_entity_reference varchar(64),
	mod_entity_reference varchar(64),
	del_entity_reference varchar(64),
	entity_status varchar(32),
	entity_is_locked char(1),
	id numeric(22,0),
	date_created date,
	user_created varchar(128),
	date_modified date,
	user_modified varchar(128),
	date_deleted date,
	audit_flag varchar(1),
	comp_rating_cov_summary numeric(22,0),
	coverage_type varchar(50),
	exposure_base varchar(4000),
	exposure_unit numeric(22,0),
	exposure numeric(22,0),
	audited_exposure numeric(22,0),
	composite_rate numeric(22,0),
	override_composite_rate numeric(22,0),
	override_reason varchar(50),
	comp_rate_formula varchar(4000),
	exposure_base_indicator numeric(22,0),
	sys_start_date date,
	sys_end_date date,
	sys_exposure_is_units char(1),
	sys_prorata numeric(22,0),
	sys_is_auditable char(1),
	sys_is_split_on_audit char(1),
	exposure_comment varchar(100),
	is_exposure_dollar varchar(128),
	comp_risk_class_code varchar(5),
	c_override_comp_rate_val numeric(22,0),
	c_termexposure numeric(22,0)
);

ALTER TABLE mic_policy_aw.rt_mis_comp_rating_summary DROP CONSTRAINT IF EXISTS rt_mis_comp_rating_summary_gid;
ALTER TABLE mic_policy_aw.rt_mis_comp_rating_summary ADD CONSTRAINT rt_mis_comp_rating_summary_gid PRIMARY KEY (gid);

