CREATE TABLE IF NOT EXISTS mic_policy_aw.mis_comp_rating_summary (
	mmy_gid numeric(22,0),
	mmy_entity_type varchar(64),
	mmy_add_entity_type varchar(64),
	mmy_mod_entity_type varchar(64),
	mmy_del_entity_type varchar(64),
	mmy_entity_reference varchar(64),
	mmy_fk_column_name varchar(64),
	mmy_fk_column_value numeric(22,0),
	mmy_add_entity_reference varchar(64),
	mmy_mod_entity_reference varchar(64),
	mmy_del_entity_reference varchar(64),
	mmy_entity_status varchar(32),
	mmy_entity_is_locked char(1),
	mmy_id numeric(22,0),
	mmy_date_created date,
	mmy_user_created varchar(128),
	mmy_date_modified date,
	mmy_user_modified varchar(128),
	mmy_date_deleted date,
	mmy_audit_flag varchar(1),
	mmy_coverage_type varchar(50),
	mmy_exposure_base varchar(4000),
	mmy_exposure_unit numeric(22,0),
	mmy_exposure numeric(22,0),
	mmy_audited_exposure numeric(22,0),
	mmy_composite_rate numeric(22,0),
	mmy_override_composite_rate numeric(22,0),
	mmy_override_reason varchar(50),
	mmy_comp_rate_formula varchar(4000),
	mmy_exposure_base_indicator numeric(22,0),
	mmy_sys_start_date date,
	mmy_sys_end_date date,
	mmy_sys_exposure_is_units char(1),
	mmy_sys_prorata numeric(22,0),
	mmy_sys_is_auditable char(1),
	mmy_sys_is_split_on_audit char(1),
	mmy_exposure_comment varchar(100),
	mmy_is_exposure_dollar varchar(128),
	mmy_comp_rating_cov_summary numeric(22,0),
	mmy_comp_risk_class_code varchar(5),
	mmy_c_override_comp_rate_val numeric(22,0),
	mmy_c_termexposure numeric(22,0)
);

ALTER TABLE mic_policy_aw.mis_comp_rating_summary DROP CONSTRAINT IF EXISTS mis_comp_rating_summary_mmy_gid;
ALTER TABLE mic_policy_aw.mis_comp_rating_summary ADD CONSTRAINT mis_comp_rating_summary_mmy_gid PRIMARY KEY (mmy_gid);

