"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_additional_pip.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_add_int_rating.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_auto_gap_coll.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_auto_gap_otc.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_av_elect_equip.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_bal_to_min_prem.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_broadened_pip.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_dealer_collision.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_dlrliab_balmin.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_extended_pip.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_ext_med_benft.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_fellow_emp.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_funeral_exp.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_ha_bal_to_min.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_leased_workers.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_liab_bal_to_min.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_liab_cl_discount.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_liab_pd.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_limited_mexico.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_limited_pr_liab.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_loss_use_expense.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_medical_benefit.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_med_pay_auto.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_nol_oth_sc_bi.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_nol_oth_sc_pd.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_non_owned_extnd.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_obel.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_otc.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_pedestrian_pip.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_pollution_liab.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_prop_insur.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_rental_reim_coll.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_rental_reim_ma.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_rental_reim_otc.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_sup_death_ben.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_tapes_records.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_towing_and_labor.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_uim.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_um.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_um_pd.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_wage_loss.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_waive_coll_ded.sql