"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_addresses.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_ca_schedule_rating.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_ca_vehicle_coverages.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_composite_rating_group.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_comp_rating_summary.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_contacts.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_coverages.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_coverages_ca.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_cov_ca_aeo_liability.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_cov_ca_collision.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_cov_ca_liability.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_cov_ca_pip.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_folder_obj_contacts_assn.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_lob_ca.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_lookups.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_policies.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_policy_financials.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_risks.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.mis_vehicles.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_addresses.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_ca_additional_coverages.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_ca_all_coverages.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_ca_vehicle_coverages.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_comp_rating_summary.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_contacts.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_busi_intrp_ratng.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_collision.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_liability.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_liab_pd.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_med_pay_auto.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_otc.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_pip.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_rent_reimburse.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_towing_and_labor.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_uim.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_cov_ca_um.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_c_submission.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_exp_rating_details.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_insureds.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_lob_ca.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_locations.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_lx_nyftz.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_producers.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_quote_policies.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_surcharges.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.rt_mis_vehicles.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.sdb_contacts.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.shl_producers.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_c_loss_prem_det.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_gl_all_coverages.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_gl_electro_data_liab.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_gl_emp_benefits_liab.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_gl_liquor_liab.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_gl_ltd_prd_withd_exp.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_gl_pollution_liability.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_gl_premops_products.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_gl_sports_participants.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_lob_gl.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_policy_comms_fees.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_quote_policies.sql
"C:\Program Files\PostgreSQL\10\bin\psql" -U postgres -d ca_st -a -f mic_policy_aw.vw_mis_vehicles.sql
